# Introdução ao Pandas (Parte 2)

## Imports

In [1]:
import pandas as pd

## Acessando os Dados

Através de operações de `dict` e `list`

In [2]:
nome_cidade = pd.Series(['Campina Grande', 'Patos', 'Sousa'])
populacao = pd.Series([399999, 1499999, 99777])

df_city = pd.DataFrame({ 'Nome da Cidade': nome_cidade, 'População': populacao })
df_city

   Nome da Cidade  População
0  Campina Grande     399999
1           Patos    1499999
2           Sousa      99777

In [3]:
type(df_city['Nome da Cidade'])

pandas.core.series.Series

In [4]:
df_city['Nome da Cidade']

0    Campina Grande
1             Patos
2             Sousa
Name: Nome da Cidade, dtype: object

In [5]:
type(df_city['Nome da Cidade'][1])

str

In [6]:
df_city['Nome da Cidade'][1]

'Patos'

In [7]:
df_city[1]['Nome da Cidade'] # erro ?!

KeyError: 1

In [8]:
type(df_city[0:2])

pandas.core.frame.DataFrame

In [9]:
df_city[0:2] # filtra as linhas, mantendo todas as colunas

   Nome da Cidade  População
0  Campina Grande     399999
1           Patos    1499999

In [10]:
df_city[0:1][0:2] # o que acontece aqui?

   Nome da Cidade  População
0  Campina Grande     399999

In [11]:
df_city['Nome da Cidade'] # filtra as colunas, mantendo todas as linhas

0    Campina Grande
1             Patos
2             Sousa
Name: Nome da Cidade, dtype: object

In [12]:
df_city[['Nome da Cidade', 'População']][0:2] # filtra as colunas, filtra as linhas

   Nome da Cidade  População
0  Campina Grande     399999
1           Patos    1499999

In [13]:
df_city[0:2][['Nome da Cidade', 'População']] # filtra as colunas, filtra as linhas (mesmo efeito do anterior)

   Nome da Cidade  População
0  Campina Grande     399999
1           Patos    1499999

#### **ATIVIDADE 6:** a função `value_counts()` só tem o parâmetro `bins` em `Series`, não tem em `DataFrame`. Escreva abaixo um código que processa o `DataFrame` `df_toy`, extraindo uma `Series` que corresponde a uma coluna com valores contínuos (apenas os 100 primeiros elementos da Serie) e aplique `value_counts()` com o parâmetro `bins` igual a 5 para ver o efeito.

Mais informações sobre a função `value_counts()` em `Series` podem ser encontradas [aqui](https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html#pandas.Series.value_counts).

In [14]:
# Caso precise realizar novamente o download e recarregar o dataframe toy_df, basta executar o código abaixo

# Opção 1: caso queira ter o arquivo CSV disponível no sistema de arquivos
# do Colab (que permanecerá disponível para esta sessão)
#
!wget -O toy_dataset.csv "https://docs.google.com/uc?export=download&id=1ArGT0_cisUUh3QXW9tYM39azFQZDUnow"
df_toy = pd.read_csv('toy_dataset.csv')
df_toy

# Opção 2
# df_toy = pd.read_csv('https://docs.google.com/uc?export=download&id=1ArGT0_cisUUh3QXW9tYM39azFQZDUnow')
# df_toy

--2026-04-19 23:28:04--  https://docs.google.com/uc?export=download&id=1ArGT0_cisUUh3QXW9tYM39azFQZDUnow
Resolving docs.google.com (docs.google.com)... 142.250.78.174, 2800:3f0:4004:812::200e
Connecting to docs.google.com (docs.google.com)|142.250.78.174|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1ArGT0_cisUUh3QXW9tYM39azFQZDUnow&export=download [following]
--2026-04-19 23:28:04--  https://drive.usercontent.google.com/download?id=1ArGT0_cisUUh3QXW9tYM39azFQZDUnow&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.78.161, 2800:3f0:4004:80d::2001
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.78.161|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5735570 (5.5M) [application/octet-stream]
Saving to: ‘toy_dataset.csv’

toy_dataset.csv     100%[===================>]   5.47M  10.2MB/s    in 0.5s

2026-04-19 23:28:06 (10.2 MB/s) - ‘toy_dataset.csv’ saved [5735570/5735570]

        Number    City  Gender  Age    Income Illness
0            1  Dallas    Male   41   40367.0      No
1            2  Dallas    Male   54   45084.0      No
2            3  Dallas    Male   42   52483.0      No
3            4  Dallas    Male   40   40941.0      No
4            5  Dallas    Male   46   50289.0      No
...        ...     ...     ...  ...       ...     ...
149995  149996  Austin    Male   48   93669.0      No
149996  149997  Austin    Male   25   96748.0      No
149997  149998  Austin    Male   26  111885.0      No
149998  149999  Austin    Male   25  111878.0      No
149999  150000  Austin  Female   37   87251.0      No

[150000 rows x 6 columns]

In [15]:
# seu código aqui (solução da atividade)
valores = df_toy['Age'].head(100)

type(valores)

pandas.core.series.Series

In [16]:
valores.value_counts(bins=5)

(40.6, 48.4]                  34
(56.2, 64.0]                  20
(24.959999999999997, 32.8]    16
(32.8, 40.6]                  16
(48.4, 56.2]                  14
Name: Age, dtype: int64

#### **ATIVIDADE 7:** Caso seus bins da questão anterior estejam desordenados. Escreva um código modificado que os exibe ordenados, para facilitar a análise.

Saída esperada:

```
(16115.5, 26667.8]     6
(26667.8, 37167.6]    21
(37167.6, 47667.4]    27
(47667.4, 58167.2]    36
(58167.2, 68667.0]    10
Name: Income, dtype: int64
```

Dica: busque na [documentação de Pandas Series](https://pandas.pydata.org/docs/reference/series.html) uma função que realiza a ordenação:

In [17]:
# seu código aqui
valores.value_counts(bins=5,sort=False)

(24.959999999999997, 32.8]    16
(32.8, 40.6]                  16
(40.6, 48.4]                  34
(48.4, 56.2]                  14
(56.2, 64.0]                  20
Name: Age, dtype: int64

## Acessando com loc e iloc

Vamos criar um novo `data_frame`

In [18]:
data_clima = [
              [25, 76.2, 1.0, 'Chuvoso'],
              [27, 76.2, 0.1, 'Chuvoso'],
              [28, 44.2, 1.1, 'Ensolarado'],
              [27, 56.2, 0.25, 'Nublado'],
              [23, 77.2, 1.1, 'Chuvoso']
            ]

df_clima = pd.DataFrame(data_clima,
                       columns=['Temperatura','Umidade','Precipitacao', 'Tempo'],
                       index=['Segunda-feira','Terça-feira','Quarta-feira', 'Quinta-feira', 'Sexta-feira']
                       )
df_clima

               Temperatura  Umidade  Precipitacao       Tempo
Segunda-feira           25     76.2          1.00     Chuvoso
Terça-feira             27     76.2          0.10     Chuvoso
Quarta-feira            28     44.2          1.10  Ensolarado
Quinta-feira            27     56.2          0.25     Nublado
Sexta-feira             23     77.2          1.10     Chuvoso

In [19]:
df_clima.loc['Segunda-feira']

Temperatura          25
Umidade            76.2
Precipitacao        1.0
Tempo           Chuvoso
Name: Segunda-feira, dtype: object

In [20]:
type(df_clima.loc['Segunda-feira'])

pandas.core.series.Series

In [21]:
df_clima.loc[0] #erro

KeyError: 0

In [22]:
df_clima.iloc[0] #OK

Temperatura          25
Umidade            76.2
Precipitacao        1.0
Tempo           Chuvoso
Name: Segunda-feira, dtype: object

In [23]:
type(df_clima.iloc[0])

pandas.core.series.Series

In [24]:
df_toy.loc[0] #erro ou OK?

Number           1
City        Dallas
Gender        Male
Age             41
Income     40367.0
Illness         No
Name: 0, dtype: object

In [25]:
df_clima.loc[['Quinta-feira'], ['Umidade']]

              Umidade
Quinta-feira     56.2

In [26]:
df_clima.iloc[3, 1]

56.2

In [27]:
df_clima.loc[['Segunda-feira','Terça-feira','Quinta-feira']] # seleciona determinadas linhas

               Temperatura  Umidade  Precipitacao    Tempo
Segunda-feira           25     76.2          1.00  Chuvoso
Terça-feira             27     76.2          0.10  Chuvoso
Quinta-feira            27     56.2          0.25  Nublado

In [28]:
df_clima.iloc[[0,1,3]] # seleciona determinadas linhas

               Temperatura  Umidade  Precipitacao    Tempo
Segunda-feira           25     76.2          1.00  Chuvoso
Terça-feira             27     76.2          0.10  Chuvoso
Quinta-feira            27     56.2          0.25  Nublado

In [29]:
df_clima.loc[['Segunda-feira','Terça-feira','Quinta-feira'],['Temperatura', 'Tempo']] # algumas linhas e algumas colunas

               Temperatura    Tempo
Segunda-feira           25  Chuvoso
Terça-feira             27  Chuvoso
Quinta-feira            27  Nublado

In [30]:
df_clima.iloc[[0,1,3],[0,3]] # algumas linhas e algumas colunas

               Temperatura    Tempo
Segunda-feira           25  Chuvoso
Terça-feira             27  Chuvoso
Quinta-feira            27  Nublado

In [31]:
df_clima.iloc[:, 0] #todas as linhas de uma coluna

Segunda-feira    25
Terça-feira      27
Quarta-feira     28
Quinta-feira     27
Sexta-feira      23
Name: Temperatura, dtype: int64

In [32]:
df_clima.loc[:, ['Temperatura', 'Tempo']] #todas as linhas de determinadas colunas

               Temperatura       Tempo
Segunda-feira           25     Chuvoso
Terça-feira             27     Chuvoso
Quarta-feira            28  Ensolarado
Quinta-feira            27     Nublado
Sexta-feira             23     Chuvoso

In [33]:
df_clima.iloc[:, [0,2]] #todas as linhas de determinadas colunas

               Temperatura  Precipitacao
Segunda-feira           25          1.00
Terça-feira             27          0.10
Quarta-feira            28          1.10
Quinta-feira            27          0.25
Sexta-feira             23          1.10

#### **ATIVIDADE 8:**

(a) escreva um código para recuperar um df contendo as linhas segunda-feira e quarta-feira, com todas as colunas, utilizando `iloc`.

(b) escreva um código equivalente usando `loc`.

In [34]:
# (a) seu código aqui
df_clima.iloc[[0,2],:]

               Temperatura  Umidade  Precipitacao       Tempo
Segunda-feira           25     76.2           1.0     Chuvoso
Quarta-feira            28     44.2           1.1  Ensolarado

In [35]:
# (b) seu código aqui

df_clima.loc[['Segunda-feira','Quarta-feira'],:]

               Temperatura  Umidade  Precipitacao       Tempo
Segunda-feira           25     76.2           1.0     Chuvoso
Quarta-feira            28     44.2           1.1  Ensolarado

## Acessando com slice

Formato start:stop:step

In [36]:
# sem step
linhas=[0,4]
df_clima.iloc[linhas, 1:3]

               Umidade  Precipitacao
Segunda-feira     76.2           1.0
Sexta-feira       77.2           1.1

In [37]:
# com step nas linhas
df_clima.iloc[0:5:2, 0:3]

               Temperatura  Umidade  Precipitacao
Segunda-feira           25     76.2           1.0
Quarta-feira            28     44.2           1.1
Sexta-feira             23     77.2           1.1

In [38]:
# Usando labels (com .loc[])
df_clima.loc['Segunda-feira':'Sexta-feira':2, 'Temperatura':'Umidade']

               Temperatura  Umidade
Segunda-feira           25     76.2
Quarta-feira            28     44.2
Sexta-feira             23     77.2

## Seleção com expressões booleanas

In [39]:
st = df_clima['Temperatura']
st

Segunda-feira    25
Terça-feira      27
Quarta-feira     28
Quinta-feira     27
Sexta-feira      23
Name: Temperatura, dtype: int64

In [40]:
st[st>26]

Terça-feira     27
Quarta-feira    28
Quinta-feira    27
Name: Temperatura, dtype: int64

In [41]:
df_clima2 = df_clima[['Temperatura', 'Umidade', 'Precipitacao']]
df_clima2

               Temperatura  Umidade  Precipitacao
Segunda-feira           25     76.2          1.00
Terça-feira             27     76.2          0.10
Quarta-feira            28     44.2          1.10
Quinta-feira            27     56.2          0.25
Sexta-feira             23     77.2          1.10

In [42]:
df_clima2[df_clima2 > 1]

               Temperatura  Umidade  Precipitacao
Segunda-feira           25     76.2           NaN
Terça-feira             27     76.2           NaN
Quarta-feira            28     44.2           1.1
Quinta-feira            27     56.2           NaN
Sexta-feira             23     77.2           1.1

In [43]:
df_clima2[df_clima2['Temperatura'] > 26]

              Temperatura  Umidade  Precipitacao
Terça-feira            27     76.2          0.10
Quarta-feira           28     44.2          1.10
Quinta-feira           27     56.2          0.25

In [44]:
df_clima2[(df_clima2['Temperatura'] > 26) & (df_clima2['Precipitacao'] < 1)] # erro se não usar parênteses

              Temperatura  Umidade  Precipitacao
Terça-feira            27     76.2          0.10
Quinta-feira           27     56.2          0.25

In [45]:
df_clima2.query('Temperatura > 26 & Precipitacao < 1')

              Temperatura  Umidade  Precipitacao
Terça-feira            27     76.2          0.10
Quinta-feira           27     56.2          0.25

In [46]:
df_clima[df_clima['Tempo'] == 'Nublado']['Temperatura']

Quinta-feira    27
Name: Temperatura, dtype: int64

In [47]:
df_clima['Temperatura'][df_clima['Tempo'] == 'Nublado']

Quinta-feira    27
Name: Temperatura, dtype: int64

In [48]:
df_clima[df_clima['Tempo'].str.startswith('C')]

               Temperatura  Umidade  Precipitacao    Tempo
Segunda-feira           25     76.2           1.0  Chuvoso
Terça-feira             27     76.2           0.1  Chuvoso
Sexta-feira             23     77.2           1.1  Chuvoso

In [49]:
df_clima[df_clima['Tempo'].isin(['Chuvoso', 'Ensolarado'])]

               Temperatura  Umidade  Precipitacao       Tempo
Segunda-feira           25     76.2           1.0     Chuvoso
Terça-feira             27     76.2           0.1     Chuvoso
Quarta-feira            28     44.2           1.1  Ensolarado
Sexta-feira             23     77.2           1.1     Chuvoso

#### **ATIVIDADE 9:**

Faça filtragem no `df_clima` de forma a retornar a Umidade de todos os registros cuja Temperatura seja 23, 27 ou 28; e o Tempo comece com 'C'.

In [50]:
# seu código aqui
df_clima[(df_clima['Temperatura'].isin([23,27,28])) & (df_clima['Tempo'].str.startswith('C'))]['Umidade']

Terça-feira    76.2
Sexta-feira    77.2
Name: Umidade, dtype: float64

## Manipulação de Linhas e Colunas (Adição, Remoção, etc)

In [51]:
# criando o data frame

d = {'primeira coluna' : pd.Series([11, 22, 32], index=['a', 'b', 'c']),
   'segunda coluna' : pd.Series([11, 22, 33, 44], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)

In [52]:
# adicionando nova coluna
df['terceira coluna']=pd.Series([100,200,300],index=['a','b','c'])
df

   primeira coluna  segunda coluna  terceira coluna
a             11.0              11            100.0
b             22.0              22            200.0
c             32.0              33            300.0
d              NaN              44              NaN

In [53]:
# criando coluna a partir de outras existentes

df['quarta coluna'] = df['primeira coluna'] + df['terceira coluna']
df

   primeira coluna  segunda coluna  terceira coluna  quarta coluna
a             11.0              11            100.0          111.0
b             22.0              22            200.0          222.0
c             32.0              33            300.0          332.0
d              NaN              44              NaN            NaN

In [54]:
# removendo uma coluna

df.pop('quarta coluna')
df

   primeira coluna  segunda coluna  terceira coluna
a             11.0              11            100.0
b             22.0              22            200.0
c             32.0              33            300.0
d              NaN              44              NaN

In [55]:
df.drop('a')

   primeira coluna  segunda coluna  terceira coluna
b             22.0              22            200.0
c             32.0              33            300.0
d              NaN              44              NaN

In [56]:
df # o que aconteceu ?

   primeira coluna  segunda coluna  terceira coluna
a             11.0              11            100.0
b             22.0              22            200.0
c             32.0              33            300.0
d              NaN              44              NaN

In [57]:
# drop também pode ser usado para colunas
df = df.drop('segunda coluna', axis=1)
df

   primeira coluna  terceira coluna
a             11.0            100.0
b             22.0            200.0
c             32.0            300.0
d              NaN              NaN

In [58]:
df2 = pd.DataFrame([[50, 60], [70, 80]], columns = ['primeira coluna','terceira coluna'])
df = df.append(df2)
df

/tmp/ipykernel_121708/4228251127.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df2)

   primeira coluna  terceira coluna
a             11.0            100.0
b             22.0            200.0
c             32.0            300.0
d              NaN              NaN
0             50.0             60.0
1             70.0             80.0

In [59]:
df2 = pd.DataFrame([[90, 99], [66, 88]], columns = ['primeira coluna','segunda coluna'])
df = df.append(df2)
df

/tmp/ipykernel_121708/4293288387.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df2)

   primeira coluna  terceira coluna  segunda coluna
a             11.0            100.0             NaN
b             22.0            200.0             NaN
c             32.0            300.0             NaN
d              NaN              NaN             NaN
0             50.0             60.0             NaN
1             70.0             80.0             NaN
0             90.0              NaN            99.0
1             66.0              NaN            88.0

####**ATIVIDADE 10:**

O dataframe da célula anterior ficou com as colunas bagunçadas (primeira/terceira/segunda).

a) Reorganize as colunas.

b) O índice das linhas também ficaram bagunçados! Reorganize-os também para ficar com numeração 0,1,2,...,n. Dica: use o método reset_index(). Depois de usar o método, veja se o dataframe ficou da forma que você esperava. Se não tiver ficado, ajuste-o.

In [60]:
# a) seu código aqui

df = pd.concat([df, df2]).reset_index(drop=True)
df

   primeira coluna  terceira coluna  segunda coluna
0             11.0            100.0             NaN
1             22.0            200.0             NaN
2             32.0            300.0             NaN
3              NaN              NaN             NaN
4             50.0             60.0             NaN
5             70.0             80.0             NaN
6             90.0              NaN            99.0
7             66.0              NaN            88.0
8             90.0              NaN            99.0
9             66.0              NaN            88.0

In [61]:
# b) seu código aqui
df

   primeira coluna  terceira coluna  segunda coluna
0             11.0            100.0             NaN
1             22.0            200.0             NaN
2             32.0            300.0             NaN
3              NaN              NaN             NaN
4             50.0             60.0             NaN
5             70.0             80.0             NaN
6             90.0              NaN            99.0
7             66.0              NaN            88.0
8             90.0              NaN            99.0
9             66.0              NaN            88.0

Isso é só um pouquinho do que o Pandas oferece no que se trata de indexação e seleção. A API do pandas é muito vasta em relação a isso.
Para mais informações, [veja aqui](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html).